@startuml
left to right direction

actor "دانشجو" as Student
actor "استاد" as Professor
actor "ادمین" as Admin

rectangle "سیستم مدیریت سایت دانشکده‌ها" {

  (ورود با شماره دانشجویی یا شناسه کارمندی) as UC1
  (ثبت زمان خروج) as UC2
  (ثبت گزارش خرابی) as UC6
  (رزرو سایت) as UC16

  (تخصیص خودکار میز یا کامپیوتر) as UC3
  (جلوگیری از تخصیص هم‌زمان) as UC4

  (مشاهده وضعیت میزها) as UC5
  (مدیریت گزارش‌های خرابی) as UC7
  (تایید رزرو) as UC17
  (جست‌وجوی پیشرفته) as UC9
  (مدیریت کاربران و نقش‌ها) as UC10
  (مدیریت نرم‌افزارها) as UC8

  (گزارش‌گیری و لاگ) as UC13
  (اعلان‌ها) as UC14
  (خروجی و ورودی داده‌ها) as UC15
}

Student -- UC1
Student -- UC2
Student -- UC6
Student -- UC14

Professor -- UC1
Professor -- UC2
Professor -- UC6
Professor -- UC16
Professor -- UC14

Admin -- UC5
Admin -- UC7
Admin -- UC17
Admin -- UC9
Admin -- UC10
Admin -- UC8
Admin -- UC14
Admin -- UC15

UC3 ..> UC1 : <<include>>
UC4 ..> UC3 : <<include>>
UC16 ..> UC17 : <<extend>>

@enduml
